import { 
  GraduationCap, 
  Flame, 
  Train, 
  Bike, 
  Plane, 
  Wheat, 
  Package, 
  HardHat, 
  HeartHandshake, 
  ShieldAlert, 
  Trophy, 
  Camera 
} from 'lucide-react';

export const USER_PERSONAS = [
  {
    id: 'student',
    number: '01',
    name: 'Student',
    title: 'Student',
    icon: GraduationCap,
    color: '#607D68',
    description: 'Campus, study and daily commute conditions',
    riskFocus: ['Heat', 'AQI', 'Rain', 'Commute'],
    recommendationHint: 'Monitors thermal strain between academic blocks and transit delays during monsoon or smog.',
    defaultMode: 'Student',
    defaultActivity: 'College'
  },
  {
    id: 'fitness',
    number: '02',
    name: 'Fitness Enthusiast',
    title: 'Fitness Enthusiast',
    icon: Flame,
    color: '#B58A45',
    description: 'Outdoor activity and exercise conditions',
    riskFocus: ['Heat', 'Humidity', 'UV', 'Exertion'],
    recommendationHint: 'Calculates metabolic heat stress, sweat loss rate, and optimal morning/evening workout windows.',
    defaultMode: 'Fitness',
    defaultActivity: 'Exercise'
  },
  {
    id: 'commuter',
    number: '03',
    name: 'Daily Commuter',
    title: 'Daily Commuter',
    icon: Train,
    color: '#718274',
    description: 'Travel and road-related environmental risks',
    riskFocus: ['Rain', 'Transit Disruption', 'Visibility'],
    recommendationHint: 'Alerts for road hydroplaning risks, delayed mass transit, and vehicle cabin heat buildup.',
    defaultMode: 'Daily Commuter',
    defaultActivity: 'Travel'
  },
  {
    id: 'cyclist',
    number: '04',
    name: 'Cyclist',
    title: 'Cyclist',
    icon: Bike,
    color: '#4F8061',
    description: 'Wind, rain, route safety and endurance conditions',
    riskFocus: ['Wind', 'Road Grip', 'Rain', 'Air Quality'],
    recommendationHint: 'Tracks aerodynamic headwind drag, wet tire traction drop, and particulate inhalation rates.',
    defaultMode: 'Fitness',
    defaultActivity: 'Cycling'
  },
  {
    id: 'traveller',
    number: '05',
    name: 'Traveller',
    title: 'Traveller',
    icon: Plane,
    color: '#8A9A83',
    description: 'Regional transit, exposure and rapid weather shifts',
    riskFocus: ['Weather Shift', 'UV', 'Heat', 'Rain'],
    recommendationHint: 'Provides localized acclimation advice and weather shifts between destinations.',
    defaultMode: 'Traveller',
    defaultActivity: 'Travel'
  },
  {
    id: 'farmer',
    number: '06',
    name: 'Farmer',
    title: 'Farmer',
    icon: Wheat,
    color: '#967D45',
    description: 'Precipitation, soil moisture, heat and seasonal cycles',
    riskFocus: ['Extreme Heat', 'Rain', 'Humidity', 'Solar'],
    recommendationHint: 'Identifies critical heat exhaustion thresholds and evapotranspiration irrigation windows.',
    defaultMode: 'Farmer',
    defaultActivity: 'Outdoor Event'
  },
  {
    id: 'delivery',
    number: '07',
    name: 'Delivery Worker',
    title: 'Delivery Worker',
    icon: Package,
    color: '#A85B5B',
    description: 'High-exposure routes, precipitation and heat stress',
    riskFocus: ['Heat', 'AQI', 'Rain', 'Road Slip'],
    recommendationHint: 'Enforces mandatory hydration checkpoints and slip hazard warnings on wet asphalt.',
    defaultMode: 'Daily Commuter',
    defaultActivity: 'Travel'
  },
  {
    id: 'outdoor_worker',
    number: '08',
    name: 'Outdoor Worker',
    title: 'Outdoor Worker',
    icon: HardHat,
    color: '#8C7752',
    description: 'Extended UV, wet bulb temperature and heavy air risk',
    riskFocus: ['Thermal Stress', 'Sunstroke', 'PM2.5'],
    recommendationHint: 'Monitors wet bulb globe temperature (WBGT) limits for heavy physical exertion.',
    defaultMode: 'Farmer',
    defaultActivity: 'Outdoor Event'
  },
  {
    id: 'parent',
    number: '09',
    name: 'Parent',
    title: 'Parent',
    icon: HeartHandshake,
    color: '#876C7A',
    description: 'Child respiratory health, heat safety and air quality',
    riskFocus: ['Air Quality', 'UV', 'Extreme Temp'],
    recommendationHint: 'Protects sensitive developing lungs from fine PM2.5 particulates and excessive solar UV index.',
    defaultMode: 'Student',
    defaultActivity: 'College'
  },
  {
    id: 'senior_citizen',
    number: '10',
    name: 'Senior Citizen',
    title: 'Senior Citizen',
    icon: ShieldAlert,
    color: '#6B7F74',
    description: 'Thermal stress, cardiovascular alert and particulate sensitivity',
    riskFocus: ['Heat Index', 'AQI', 'Cold Snaps'],
    recommendationHint: 'Applies stricter cardiovascular safety margins against sudden thermal swings and smog.',
    defaultMode: 'Daily Commuter',
    defaultActivity: 'Travel'
  },
  {
    id: 'athlete',
    number: '11',
    name: 'Athlete',
    title: 'Athlete',
    icon: Trophy,
    color: '#437255',
    description: 'Peak performance windows, hydration and oxygen metrics',
    riskFocus: ['Thermal Regulation', 'Hydration', 'Humidity'],
    recommendationHint: 'Calculates fluid deficit per hour and identifies optimal peak physiological performance hours.',
    defaultMode: 'Fitness',
    defaultActivity: 'Exercise'
  },
  {
    id: 'photographer',
    number: '12',
    name: 'Photographer',
    title: 'Photographer',
    icon: Camera,
    color: '#5C6B61',
    description: 'Golden hour, lighting, visibility and atmospheric clarity',
    riskFocus: ['Cloud Cover', 'Golden Hour', 'Rain', 'Fog'],
    recommendationHint: 'Forecasts solar angles, atmospheric haze, cloud diffusion, and sudden rain squalls.',
    defaultMode: 'Traveller',
    defaultActivity: 'Outdoor Event'
  }
];
